### ISSUE TITLE
Add ability to define private function with defrec

### ISSUE THREAD

**Issue by enforser** [divs1210/xodarap#2]
It would be nice to have the ability to define a private function with `defrec`. 
Maybe through `defrec-` or `(defrec ^:private ...)`

**Comment by divs1210** [comment]
Hi @enforser!
I believe you were correct in suggesting `defrec-`, because the internal `defn` can't be annotated from outside.
You can send in a PR for this if you have the time.
Sorry for the hassle, and thanks for your PRs!

**Comment by enforser** [comment]
No worries! I'll throw up a PR for `defrec-` in the couple of days.
