### ISSUE TITLE
Add letrec

### ISSUE THREAD

**Issue by divs1210** [divs1210/xodarap#7]
For local functions.
Not really required, but might be a nice thing to have.

**Comment by enforser** [comment]
Would also be awesome to be able to define a xodarap rec function anonymously as well. I'm wondering if the "helper" function could be stored in the metadata of the recursive function - this would allow anonymous functions to be defined in a normal clojure let binding.

**Comment by divs1210** [comment]
That's an interesting idea, and something I have thought a bit about.
The metadata idea also sounds interesting - it could allow instrumenting existing `defn`s without changing the source (using `defrec`s).

**Comment by divs1210** [comment]
Fixed in https://github.com/divs1210/xodarap/commit/83c67590e8e007aac021b13d47264679f512f414
